# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Yang Shu
description: >- # this means to ignore newlines until "baseurl:"
  A page of me.
baseurl: "" # the subpath of the site
url: "https://foolLain.github.io" # the base hostname & protocol for the site
og_image: /assets/img/rei.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: foollain@zju.com
      link: mailto:foollain@zju.com

  follow:
    - name: keybase
      value: ZJU
      link: https://www.zju.edu.cn/
      
    - name: GitHub
      link: http://github.com/foollain

    - name: Zeqing Wang@sysu
      link: https://www.naptmn.cn/

    - name: Jialiang Wang@hit
      link: https://jialiang-wang2002.github.io/

    - name: Shuang Liang@whu
      link: https://whusliang.com/
      


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
